site_name: Dryad2dataverse
docs_dir: 'docs'
nav:
  - Overview: index.md
  - Installation: installation.md
  - The dryadd console application: script.md
  - Other utilities: other_utils.md
  - Compiling or packaging the application: compiling.md
  - General Reference: reference.md
  - API Reference: api_reference.md
    #- Tracking Database Structure: dbase_structure/index.html
  - Tracking Database Structure: track.md 
  - Changelog: changelog.md
  - FAQ: faq.md
  - Credits: credits.md
extra_css:
  - css/extra.css
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - codehilite:
      guess_lang: False
      linenums: False
      use_pygments: False
  - attr_list

theme: readthedocs
