site_name: Local Preview Dryad2dataverse
docs_dir: 'docs'
nav:
  - Overview: index.md
  - Installation: installation.md
  - Sample Files: samples.md
  - General Reference: reference.md
  - API Reference: api_reference.md
  - FAQ: faq.md
  - Acknowledgements: acknowledgements.md
theme: readthedocs 
