site_name: Dryad2dataverse
docs_dir: 'docs'
nav:
  - Overview: index.md
  - installation.md
  - dryadd.md
  - api_reference.md
    #- Tracking Database Structure: dbase_structure/index.html
  - Tracking database structure: track.md 
  - other_utils.md
  - FAQ: faq.md
  - Credits: credits.md
extra_css:
  - css/extra.css
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - codehilite:
      guess_lang: False
      linenums: False
      use_pygments: False
  - attr_list

theme: readthedocs

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            docstring_style: numpy
            show_source: true
            filters: public
  - search
