site_name: Dryad2dataverse
docs_dir: 'docs'
nav:
  - Overview: index.md
  - Installation: installation.md
  - Command line script: scripts.md
  - General Reference: reference.md
  - API Reference: api_reference.md
    #- Tracking Database Structure: dbase_structure/index.html
  - Tracking Database Structure: track.md 
  - Changelog: changelog.md
  - FAQ: faq.md
  - Credits: credits.md

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - codehilite
  - attr_list

theme: readthedocs
